FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# OrizonHub

See also: https://github.com/gumblex/orizonhub

## Group Messenging

### General Settings [/settings]

#### Get Current Setting [GET]

+ Headers
        X-APIKey: <Your_API_KEY>

+ Response 200 (application/json)

    + Attributes (object)
        + id (number, required) - Bot ID
        + name (string, required) - Bot name
        + type (enum[string], required) - Bot type

            + Members
                + `protocol_bridge`
                + `public_service`
                + `logger`

        + admin (string, required) - userID of bot admin
        + hooks (array) - what message should the bot get
        + scope (array) - permissions of api request
        + mode (enum[string]) - bot mode

            + Members
                + `online`
                + `offline`
                + `maintenance`

    + Body
        {
            "id": 0,
            "name": "Tox",
            "type": "protocol_bridge",
            "admin": "tox: quininer",
            "hooks": ["protocol.all.message"],
            "scope": ["userdb.get", "userdb.put"],
            "mode": "online"
        }

#### Update Settings [POST]

+ Request (application/json)

        {
            "id": 0,
            "name": "Tox",
            "type": "protocol_bridge",
            "admin": "tox: quininer",
            "hooks": ["protocol.all.message"],
            "scope": ["userdb.get", "userdb.put"],
            "mode": "online"
        }

+ Response 200 (application/json)

            {
                "_": 200
            }