FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# OrizonHub

See also: https://github.com/gumblex/orizonhub

## Group Messenging

### General Settings [/settings]

#### Get Current Setting [GET]

+ Headers
        X-APIKey: <Your_API_KEY>

+ Response 200 (application/json)

    + Attributes (object)
        + id (int) - Bot ID
        + name (string) - Bot name
        + type (enum[string]) - Bot type
            + Members
                + `protocol_bridge`
                + `public_service`
                + `logger`
        + admin (string) - userID of bot admin
        + hooks (array) - what message should the bot get
        + scope (array) - permissions of api request
        + mode (enum[string]) - bot mode
            + Members
                + `online`
                + `offline`
                + `maintenance`

    + Body
        {
            "id": 0,
            "name": "Tox",
            "type": "protocol_bridge",
            "admin": "tox: quininer",
            "hooks": ["protocol.all.message"],
            "scope": ["userdb.get", "userdb.put"],
            "mode": "online"
        }

#### Create a New Question [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }